apiVersion: devops/v1alpha2
kind: MicroService
group: com.hand.hapcloud
code: hap-manager-service
name: 微服务管理服务
version: ${VERSION}
image: registry.digital.saas.carllhw.com/hapcloud/hap-manager-service:${IMAEG_TAG}
commit: ${COMMIT}
gatewayPath: "/manager/**"

vars:
- name: memory_limits
  description: "内存上限"
  value: "2560Mi"
- name: memory_requests
  description: "内存请求"
  value: "1536Mi"

services:
- kind: MicroService
  group: com.hand.hapcloud
  code: hap-register-server
  require: 1

resources:
- name: db
  type: mysql
- name: userdb
  type: mysql
- name: rabbitmq
  type: rabbitmq
- name: swagger_oauth_url
  type: url
- name: eureka
  type: url

stages:
- name: 初始化数据库
  type: PrepareDB
  description: "初始化当前服务数据库和用户服务数据库"
  config:
    db:
    - name: 初始化当前服务数据库
      host: "{{ db.HOST }}"
      port: "{{ db.PORT }}"
      schema: "{{ db.SCHEMA }}"
      username: "{{ db.USERNAME }}"
      password: "{{ db.PASSWORD }}"
      dataJar: /app.jar
    - name: 初始化用户服务数据库
      host: "{{ userdb.HOST }}"
      port: "{{ userdb.PORT }}"
      schema: "{{ userdb.SCHEMA }}"
      username: "{{ userdb.USERNAME }}"
      password: "{{ userdb.PASSWORD }}"
      dataDir: /hap-user-service-db
- name: 部署
  type: Deploy
  description: "部署当前服务"
  config:
    port: 8963
    managementPort: 8964
    env:
    - name: SPRING_DATASOURCE_USERNAME
      value: "{{ db.USERNAME }}"
    - name: SPRING_DATASOURCE_PASSWORD
      value: "{{ db.PASSWORD }}"
    - name: SPRING_PROFILES_ACTIVE
      value: sit
    - name: EUREKA_DEFAULT_ZONE
      value: "{{eureka.HOST}}"
    - name: SPRING_RABBITMQ_HOST
      value: "{{rabbitmq.HOST}}"
    - name: SWAGGER_OAUTHURL
      value: "{{ swagger_oauth_url.HOST }}"
    - name: SPRING_DATASOURCE_URL
      value: "jdbc:mysql://{{ db.HOST }}:{{ db.PORT }}/{{ db.SCHEMA }}?useUnicode=true&characterEncoding=utf-8&useSSL=false"
    resources:
      limits:
        memory: "{{ vars.memory_limits }}"
      requests:
        memory: "{{ vars.memory_requests }}"
    readinessProbe:
      httpGet:
        path: /health
        port: 8964
        scheme: HTTP
      failureThreshold: 3
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
