spring:
  datasource:
    url: jdbc:mysql://localhost/manager_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hapcloud
    password: handhand
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          zkNodes: 127.0.0.1:2181
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8000/eureka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      group-id: manager-server
      auto-offset-reset: latest
    listener:
      ack-mode: manual_immediate
      poll-timeout: 3000
choerodon:
  swagger:
    oauth-url: http://localhost:8080/oauth/oauth/authorize
    skip:
      service: register-server, api-gateway, gateway-helper, oauth-server, config-server, event-store-service
  gateway:
    domain: 127.0.0.1:8080
    names: api-gateway, gateway-helper
#logging:
#  level:
#   io.choerodon.manager: debug